import Head from 'next/head'
import CurrentTime from '../components/CurrentTime'
import RouteSection from '../components/RouteSection'

export default function Home () {
  // const dataToLoad = [
  //   { routeId: '40_100479', stopId: '1_990004' },
  //   { routeId: '40_100479', stopId: '1_990003' },
  //   { routeId: '1_100225', stopId: '1_36940' },
  //   { routeId: '1_100252', stopId: '1_36940' },
  //   { routeId: '1_100252', stopId: '1_16430' },
  //   { routeId: '1_100225', stopId: '1_16430' }
  // ]

  return (
    <div>
      <Head>
        <title>Waysign</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='bg-black h-screen w-screen text-white'>
        <section className='w-full h-24 bg-blue-900 flex text-7xl justify-between items-center px-6'>
          <div>Roosevelt Station</div>
          <CurrentTime />
        </section>
        <section className='grid grid-cols-2 gap-y-4 p-4 justify-items-stretch w-full'>
          <RouteSection routeName={1} color='#1FBB00' />
          <RouteSection routeName={1} color='#1FBB00' />
          <RouteSection routeName={62} type='square' color='#2519ff' />
          <RouteSection routeName={45} type='square' color='#2519ff' />
        </section>
      </main>
    </div>
  )
}
