import Head from 'next/head'
import Column from '../lib/Column'
import CurrentTime from '../lib/CurrentTime'
import config from '../config.yaml'
import { useState } from 'react'
export default function Home () {
  // an easter egg
  const [fontIndex, setFontIndex] = useState(0)
  const updateFontIndex = () => {
    setFontIndex(fontIndex + 1)
  }
  const getFontClass = () => {
    switch (fontIndex % 3) {
      case 0:
        return 'font-sans'
      case 1:
        return 'font-sansAlt'
      case 2:
        return 'font-sansAlt2'
    }
  }
  return (
    <div className={getFontClass()}>
      <Head>
        <title>{config.title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='bg-black md:h-screen md:w-screen text-white'>
        <section
          onClick={updateFontIndex}
          className='w-full md:h-24 bg-blue-900 flex md:text-7xl text-xl justify-between items-center px-6'
        >
          <div>{config.title}</div>
          <CurrentTime />
        </section>
        <section className='md:grid md:grid-cols-3 h-full w-full justify-items-stretch'>
          {config.columns.map((col, i) => (<Column key={i} col={col} />))}
        </section>
      </main>
    </div>
  )
}
