import Head from 'next/head'
import Column from '../lib/Column'
import CurrentTime from '../lib/CurrentTime'
import config from '../config.yaml'
export default function Home () {
  return (
    <div>
      <Head>
        <title>{config.title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='bg-black h-screen w-screen text-white'>
        <section className='w-full h-24 bg-blue-900 flex text-7xl justify-between items-center px-6'>
          <div>{config.title}</div>
          <CurrentTime />
        </section>
        <section className='grid grid-cols-3 h-full w-full justify-items-stretch'>
          {config.columns.map((col, i) => (<Column key={i} col={col} />))}
        </section>
      </main>
    </div>
  )
}
